# -*- coding: utf-8 -*-
"""AgenteRag.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E4uv4zE96hQciJ0Wvfi8gPGmPe5dajZq
"""

# Instalar librerías necesarias
!pip install -q mistralai langchain langchain-mistralai chromadb sentence-transformers pandas langchain_community langchain-text-splitters langchain-huggingface langchain-experimental chardet
# Reiniciar runtime si es necesario (opcional, pero recomendado)
#import os
#os.kill(os.getpid(), 9)
#!pip install mistralai

"""Configurar el ApiKey + Conexion"""

from google.colab import userdata
import os
from mistralai.client import Mistral

API_KEY = userdata.get('PruebaIA')
os.environ["MISTRAL_API_KEY"] = API_KEY

client = Mistral(api_key=API_KEY)
response = client.chat.complete(
    model="mistral-small-latest",
    messages=[{"role": "user", "content": "Responde 'OK'"}],
    max_tokens=10
)
print(f"✓ Conexión Mistral: {response.choices[0].message.content}")

"""Carga mas validacion del dataset"""

import pandas as pd
import chardet

with open('sales_data_normalizado.csv', 'rb') as f:
    encoding = chardet.detect(f.read())['encoding']

df = pd.read_csv('sales_data_normalizado.csv', encoding=encoding)
print(f"✓ Dataset: {df.shape[0]} filas × {df.shape[1]} columnas")

nulos = df.isnull().sum()
nulos_totales = nulos[nulos > 0]
duplicados = df['ORDERNUMBER'].duplicated().sum()
df['ORDERDATE'] = pd.to_datetime(df['ORDERDATE'])

print(f"✓ Validación | Nulos: {len(nulos_totales)} columnas | Duplicados: {duplicados}")
print(f"  Fechas: {df['ORDERDATE'].min().date()} a {df['ORDERDATE'].max().date()}")
print(f"  Países: {df['COUNTRY'].nunique()} | Productos: {df['PRODUCTLINE'].nunique()}")

"""Corpus para el RAG"""

from langchain_core.documents import Document

def crear_corpus(df, max_reg=500):
    docs = []
    for idx, row in df.head(max_reg).iterrows():
        texto = f"""VENTA #{row['ORDERNUMBER']}
Producto: {row['PRODUCTLINE']} | Cantidad: {int(row['QUANTITYORDERED'])}
Venta: ${row['SALES']:.2f} | Estado: {row['STATUS']}
País: {row['COUNTRY']} | Fecha: {row['ORDERDATE'].date()}
Tamaño: {row['DEALSIZE']} | Cliente: {row['CUSTOMERNAME']}"""

        docs.append(Document(
            page_content=texto,
            metadata={
                "order": int(row['ORDERNUMBER']),
                "sales": float(row['SALES']),
                "country": row['COUNTRY'],
                "status": row['STATUS'],
                "product": row['PRODUCTLINE']
            }
        ))
    return docs

corpus = crear_corpus(df, max_reg=500)
print(f"✓ Corpus: {len(corpus)} documentos")

"""Vector store"""

from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2",
    model_kwargs={'device': 'cpu'}
)

vectorstore = Chroma.from_documents(
    documents=corpus,
    embedding=embeddings,
    persist_directory="./chroma_sales_db"
)

# ===== CREACIÓN DEL RETRIEVER =====
retriever = vectorstore.as_retriever(
    search_type="similarity",
    search_kwargs={"k": 4}
)

print(f"✓ Vector Store: {vectorstore._collection.count()} vectores")
print(f"✓ Retriever configurado: búsqueda por similitud, k=4")

# ===== PRUEBA DEL RETRIEVER (AQUÍ SE AGREGA) =====
print("\n🔍 Probando retriever...")
pregunta_test = "ventas en Australia"
docs_recuperados = retriever.invoke(pregunta_test)

print(f"  Pregunta: '{pregunta_test}'")
print(f"  Documentos recuperados: {len(docs_recuperados)}")
for i, doc in enumerate(docs_recuperados, 1):
    print(f"  {i}. Orden #{doc.metadata.get('order')} | {doc.metadata.get('country')} | ${doc.metadata.get('sales', 0):,.2f}")
print("✓ Retriever funcionando correctamente\n")

"""Agente pandas con prefix detallado"""

from langchain_experimental.agents import create_pandas_dataframe_agent
from langchain_mistralai import ChatMistralAI

llm = ChatMistralAI(api_key=API_KEY, model="mistral-small-latest", temperature=0.1)

PREFIX = """Eres un analista senior de datos de ventas con acceso a un DataFrame de pandas llamado 'df'.

ESTRUCTURA DEL DATASET:
El DataFrame contiene {filas} registros de ventas con las siguientes columnas:

COLUMNAS NUMÉRICAS (análisis cuantitativo):
- ORDERNUMBER: Identificador único de orden (INT)
- QUANTITYORDERED: Cantidad de productos ordenados (INT)
- PRICEEACH: Precio unitario en dólares (FLOAT)
- SALES: Monto total de la venta en dólares (FLOAT)
- MSRP: Precio sugerido por el fabricante (FLOAT)
- QTR_ID: Trimestre del año 1-4 (INT)
- MONTH_ID: Mes del año 1-12 (INT)
- YEAR_ID: Año de la orden (INT)

COLUMNAS CATEGÓRICAS (segmentación):
- STATUS: Estado del pedido [Shipped, Cancelled, Resolved, On Hold, Disputed, In Process]
- DEALSIZE: Tamaño del negocio [Small, Medium, Large]
- PRODUCTLINE: Línea de producto [Motorcycles, Classic Cars, Trucks and Buses, Vintage Cars, Planes, Ships, Trains]
- PRODUCTCODE: Código único del producto
- COUNTRY: País del cliente ({paises} países)
- CITY: Ciudad del cliente
- TERRITORY: Territorio geográfico [EMEA, APAC, Americas, etc.]
- CUSTOMERNAME: Nombre del cliente
- CONTACTLASTNAME: Apellido del contacto
- CONTACTFIRSTNAME: Nombre del contacto

COLUMNAS DE FECHA:
- ORDERDATE: Fecha completa de la orden (YYYY-MM-DD)

REGLAS DE ANÁLISIS:
1. USA EXCLUSIVAMENTE pandas/numpy para TODOS los cálculos
2. SIEMPRE verifica el resultado antes de responder:
   - Revisa que no haya NaN o valores infinitos
   - Confirma que las sumas cuadren
   - Valida que los porcentajes sumen 100%
3. FORMATEA RESPUESTAS:
   - Montos: usa formato monetario ($12,345.67)
   - Porcentajes: redondea a 1 decimal (23.5%)
   - Tablas: usa formato markdown cuando sea posible
4. MANEJO DE ERRORES:
   - Si una columna no existe, indícalo claramente
   - Si hay datos insuficientes, menciona cuántos registros hay
   - Si el resultado es cero o vacío, verifica dos veces
5. INSIGHTS ADICIONALES:
   - Agrega contexto relevante (ej: "esto representa el X% del total")
   - Identifica outliers o patrones interesantes
   - Compara con promedios generales cuando sea útil
6. LIMITACIONES:
   - No inventes datos, solo usa lo que está en el DataFrame
   - Si no puedes responder con precisión, explica qué limitación encuentras

ESTADÍSTICAS RÁPIDAS DEL DATASET:
- Rango de fechas: {fecha_min} a {fecha_max}
- Venta total: ${venta_total:,.0f}
- Ticket promedio: ${ticket_promedio:,.2f}
- Países con más ventas: {top_paises}

Responde siempre en español, con precisión y claridad."""

# Preparar estadísticas para el prefix
fecha_min = df['ORDERDATE'].min().date()
fecha_max = df['ORDERDATE'].max().date()
venta_total = df['SALES'].sum()
ticket_promedio = df['SALES'].mean()
top_paises = df['COUNTRY'].value_counts().head(3).index.tolist()
paises = df['COUNTRY'].nunique()

PREFIX = PREFIX.format(
    filas=len(df),
    paises=paises,
    fecha_min=fecha_min,
    fecha_max=fecha_max,
    venta_total=venta_total,
    ticket_promedio=ticket_promedio,
    top_paises=", ".join(top_paises)
)

pandas_agent = create_pandas_dataframe_agent(
    llm=llm,
    df=df,
    prefix=PREFIX,
    verbose=False,
    allow_dangerous_code=True,
    agent_type="tool-calling",
    max_iterations=8,
    handle_parsing_errors=True
)
print("✓ Agente Pandas creado con prefix detallado")

"""Sistema RAG"""

from langchain_mistralai import ChatMistralAI
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough

class RAGMistral:
    def __init__(self, retriever, api_key, model="mistral-small-latest"):
        self.retriever = retriever
        self.client = Mistral(api_key=api_key)
        self.model = model

        # Template para el prompt
        self.prompt_template = """Eres un analista de ventas experto.
Responde SOLO con datos del contexto proporcionado.

CONTEXTO RECUPERADO:
{context}

PREGUNTA DEL USUARIO:
{question}

INSTRUCCIONES:
- Usa solo información del contexto
- Cita números de orden y montos específicos
- Si no hay suficiente información, indícalo claramente
- Responde en español

RESPUESTA:"""

    def formatear_docs(self, docs):
        """Formatea los documentos recuperados en un solo texto"""
        return "\n\n---\n\n".join([doc.page_content for doc in docs])

    def consultar(self, pregunta):
        # 1. RECUPERAR documentos relevantes usando el retriever
        docs_relevantes = self.retriever.invoke(pregunta)

        # 2. Formatear contexto
        contexto = self.formatear_docs(docs_relevantes)

        # 3. Crear prompt completo
        prompt_completo = self.prompt_template.format(
            context=contexto,
            question=pregunta
        )

        # 4. Generar respuesta con Mistral
        response = self.client.chat.complete(
            model=self.model,
            messages=[
                {"role": "system", "content": "Eres un analista de ventas experto."},
                {"role": "user", "content": prompt_completo}
            ],
            temperature=0.2,
            max_tokens=500
        )

        respuesta = response.choices[0].message.content

        # 5. Extraer fuentes
        fuentes = []
        for doc in docs_relevantes:
            fuentes.append({
                "order": doc.metadata.get('order'),
                "sales": doc.metadata.get('sales'),
                "country": doc.metadata.get('country'),
                "status": doc.metadata.get('status'),
                "product": doc.metadata.get('product')
            })

        return respuesta, fuentes, docs_relevantes

rag = RAGMistral(retriever, API_KEY)
print("✓ Sistema RAG listo con Retriever")

"""Sistema Unificado"""

class AsistenteVentas:
    def __init__(self, agent, rag, df, retriever):
        self.agent = agent
        self.rag = rag
        self.df = df
        self.retriever = retriever
        self.historial = []

    def preguntar(self, pregunta):
        # Decisión de método
        keywords_agente = [
            'total', 'promedio', 'suma', 'máximo', 'mínimo',
            'top', 'ranking', 'porcentaje', 'agrupar', 'distribución',
            'estadística', 'cuántos', 'cuántas', 'contar'
        ]

        pregunta_lower = pregunta.lower()
        metodo = "rag"

        if any(kw in pregunta_lower for kw in keywords_agente):
            metodo = "agente"

        if metodo == "agente":
            try:
                resp = self.agent.invoke(pregunta)
                respuesta = str(resp['output']) if isinstance(resp, dict) else str(resp)
                fuentes = None
            except Exception as e:
                # Fallback a RAG con retriever
                respuesta, fuentes, docs = self.rag.consultar(pregunta)
                metodo = "rag (fallback)"
        else:
            respuesta, fuentes, docs = self.rag.consultar(pregunta)

        self.historial.append({
            "pregunta": pregunta,
            "respuesta": respuesta,
            "metodo": metodo,
            "num_docs": len(fuentes) if fuentes else 0
        })

        return respuesta, metodo

asistente = AsistenteVentas(pandas_agent, rag, df, retriever)
print("✓ Sistema unificado listo con Retriever\n")

"""Pruebas"""

preguntas = [
    "¿Total de ventas por país? Dame el top 5",
    "¿Cuál es el ticket promedio por línea de producto?",
    "¿Distribución porcentual de estados de pedidos?",
    "Muéstrame detalles de órdenes de Australia con deal size Large",
    "¿Cuál fue el mes con mayores ventas y cuánto representó del total?"
]

for i, pregunta in enumerate(preguntas, 1):
    resp, metodo = asistente.preguntar(pregunta)
    print(f"\n{'='*50}")
    print(f"Q{i}: {pregunta}")
    print(f"[{metodo.upper()}] {resp[:250]}...")

"""Chat Interactivo"""

print("\n💬 CHAT DE VENTAS | stats | validar | salir")

while True:
    pregunta = input("\n🔍 Tú: ").strip()

    if pregunta.lower() in ['salir', 'exit']:
        break

    if pregunta.lower() == 'stats':
        print(f"  Consultas: {len(asistente.historial)}")
        print(f"  Dataset: {len(df)} filas | {df['COUNTRY'].nunique()} países")
        print(f"  Venta total: ${df['SALES'].sum():,.0f}")
        continue

    if pregunta.lower() == 'validar':
        print(f"  Nulos: {df.isnull().sum().sum()} | Duplicados: {df['ORDERNUMBER'].duplicated().sum()}")
        print(f"  Rango: {df['ORDERDATE'].min().date()} → {df['ORDERDATE'].max().date()}")
        continue

    if not pregunta:
        continue

    resp, metodo = asistente.preguntar(pregunta)
    print(f"🤖 [{metodo}] {resp}")